name: design_patterns
description: The aim of this project is to demonstrate the design patterns in Dart using simple examples.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
